from django.core.exceptions import ValidationError

def validate_class()